"""empty message

Revision ID: 350dc87c6683
Revises: 73b02428f846
Create Date: 2020-10-06 20:36:01.220997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350dc87c6683'
down_revision = '73b02428f846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
